version: "3"

services:

  app:
    image: horns:latest
    command: yarn develop:docker
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      VIRTUAL_HOST: horns.local
