export default {
  families: {
    primary: {
      base: 'Helvetica',
      fallback: 'sans-serif',
      kerning: '', // letter-spacing
      tracking: '', // word-spacing
    },
    secondary: {
      base: 'Times New Roman',
      fallback: 'serif',
      kerning: '',
      tracking: '',
    },
    tertiary: {
      base: 'Monaco',
      fallback: 'monospace',
      kerning: '',
      tracking: '',
    },
  },
  decorations: {
    none: {
      line: 'none',
      style: '',
    },
    overline: {
      line: 'overline',
      style: '',
    },
    underline: {
      line: 'underline',
      style: '',
    },
    wave: {
      line: 'underline',
      style: 'wavy',
    },
    strikeThrough: {
      line: 'line-through',
      style: '',
    },
  },
  weights: {
    base: 400,
    lighter: 100,
    light: 200,
    semiBold: 600,
    bold: 700,
    bolder: 900,
  },
  sizes: {
    base: 'medium',
    small: '0.75em',
    large: '1.5em',
    // Min and max are used for body font size scaling with all other sizes being calculated from that using ems.
    min: '12px',
    max: '16px',
    h1: '3.21em',
    h2: '2.36em',
    h3: '1.64em',
    h4: '1.29em',
    h5: '1.15em',
    h6: '1em',
  },
  // margin; space before and after the text
  spacing: {
    base: '0',
    paragraph: '1em 0',
    heading: '0.67em 0 0.67em 0',
  },
  // line-height
  letting: {
    base: '1.6em',
    min: '1em',
    max: '2em',
  },
  indent: {
    base: 'inherit',
    paragraph: '1em',
  },
  tracking: {
    base: 'normal',
  },
  styles: {
    paragraph: {
      family: 'primary',
      style: 'normal',
      weight: 'base',
      size: 'base',
      align: 'justify',
      justify: 'auto',
      transform: 'none',
      decoration: 'none',
      // these are modifiers for the base value provided by the typeface.
      kerning: 'base',
      tracking: 'base',
      letting: 'base',
      hover: {
        decoration: 'none',
      },
      active: {
        decoration: 'none',
      },
    },
    heading: {
      family: 'primary',
      style: 'normal',
      weight: 'bold',
      // Size is intentionally blank; heading size is set based on the level prop.
      size: '',
      align: 'left',
      justify: 'none',
      transform: 'none',
      decoration: 'none',
      kerning: 'base',
      tracking: 'base',
      letting: 'min',
      hover: {
        decoration: 'none',
      },
      active: {
        decoration: 'none',
      },
    },
    quote: {
      family: 'primary',
      style: 'italic',
      weight: 'base',
      size: 'base',
      align: 'left',
      justify: 'none',
      transform: 'none',
      decoration: 'none',
      kerning: 'base',
      tracking: 'base',
      letting: 'base',
      hover: {
        decoration: 'none',
      },
      active: {
        decoration: 'none',
      },
    },
    text: {
      family: 'primary',
      style: 'normal',
      weight: 'base',
      size: 'base',
      align: 'left',
      justify: 'none',
      transform: 'none',
      decoration: 'none',
      kerning: 'base',
      tracking: 'base',
      letting: 'base',
      hover: {
        decoration: 'none',
      },
      active: {
        decoration: 'none',
      },
    },
    label: {
      family: 'primary',
      style: 'normal',
      weight: 'bold',
      size: 'base',
      align: 'left',
      justify: 'none',
      transform: 'none',
      decoration: 'none',
      kerning: 'base',
      tracking: 'base',
      letting: 'min',
      hover: {
        decoration: 'none',
      },
      active: {
        decoration: 'none',
      },
    },
    message: {
      family: 'primary',
      style: 'normal',
      weight: 'base',
      size: 'base',
      align: 'left',
      justify: 'none',
      transform: 'none',
      decoration: 'none',
      kerning: 'base',
      tracking: 'base',
      letting: 'base',
      hover: {
        decoration: 'none',
      },
      active: {
        decoration: 'none',
      },
    },
    button: {
      family: 'primary',
      style: 'normal',
      weight: 'bold',
      size: 'base',
      align: 'left',
      justify: 'none',
      transform: 'none',
      decoration: 'none',
      kerning: 'base',
      tracking: 'base',
      letting: 'base',
      hover: {
        decoration: 'none',
      },
      active: {
        decoration: 'none',
      },
    },
    link: {
      family: 'primary',
      style: 'normal',
      weight: 'base',
      size: 'base',
      align: 'left',
      justify: 'none',
      transform: 'none',
      decoration: 'none',
      kerning: 'base',
      tracking: 'base',
      letting: 'base',
      hover: {
        decoration: 'underline',
      },
      active: {
        decoration: 'underline',
      },
    },
    caption: {
      family: 'primary',
      style: 'normal',
      weight: 'light',
      size: 'base',
      align: 'left',
      justify: 'none',
      transform: 'none',
      decoration: 'none',
      kerning: 'base',
      tracking: 'base',
      letting: 'base',
      hover: {
        decoration: 'none',
      },
      active: {
        decoration: 'none',
      },
    },
    legal: {
      family: 'secondary',
      style: 'italic',
      weight: 'base',
      size: 'small',
      align: 'left',
      justify: 'none',
      transform: 'none',
      decoration: 'none',
      kerning: 'base',
      tracking: 'base',
      letting: 'base',
      hover: {
        decoration: 'none',
      },
      active: {
        decoration: 'none',
      },
    },
    code: {
      family: 'tertiary',
      style: 'normal',
      weight: 'base',
      size: 'base',
      align: 'left',
      justify: 'none',
      transform: 'none',
      decoration: 'none',
      kerning: 'base',
      tracking: 'base',
      letting: 'base',
      hover: {
        decoration: 'none',
      },
      active: {
        decoration: 'none',
      },
    },
    emphasized: {
      family: 'primary',
      style: 'italic',
      weight: 'base',
      size: 'base',
      align: 'left',
      justify: 'none',
      transform: 'none',
      decoration: 'none',
      kerning: 'base',
      tracking: 'base',
      letting: 'base',
      hover: {
        decoration: 'none',
      },
      active: {
        decoration: 'none',
      },
    },
    strong: {
      family: 'primary',
      style: 'normal',
      weight: 'bold',
      size: 'base',
      align: 'left',
      justify: 'none',
      transform: 'none',
      decoration: 'none',
      kerning: 'base',
      tracking: 'base',
      letting: 'base',
      hover: {
        decoration: 'none',
      },
      active: {
        decoration: 'none',
      },
    },
    variable: {
      family: 'tertiary',
      style: 'italic',
      weight: 'base',
      size: 'base',
      align: 'left',
      justify: 'none',
      transform: 'none',
      decoration: 'none',
      kerning: 'base',
      tracking: 'base',
      letting: 'base',
      hover: {
        decoration: 'none',
      },
      active: {
        decoration: 'none',
      },
    },
  },
}
